# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13cc6966160ab5d5eaf5ddc999fb054b2c3cda819297b1e31d6191c5468b8ed9a1680b0736a58b064775541be7cfa87fb7ad41fb7ada86d50dec131b82b844cd

test:
  secret_key_base: 0b811f083d6fbbc47c9aa4db7a49e076555fe6e0b4acfac7b4de3efc108e3b26881be370611b59115c300ed3d07a900afc4156bbc738fe3aa69acbbd8cefa0ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
